*** Starting uWSGI 2.0.15 (32bit) on [Sat Jul 15 13:24:51 2017] ***
compiled with version: 5.4.0 20160609 on 14 July 2017 20:12:54
os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:57:27 UTC 2017
nodename: iZ2zeg872luz0mzt03kfxzZ
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/flask/flask_blog-python3
writing pidfile to /var/run/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/flask/flask_blog-python3
your processes number limit is 7738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9163 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x88ccc60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 575856 bytes (562 KB) for 8 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 14, in <module>
    from models import User
  File "./app/models.py", line 4, in <module>
    from app import db,app
ImportError: cannot import name db
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4858)
spawned uWSGI worker 1 (pid: 4861, cores: 1)
spawned uWSGI worker 2 (pid: 4862, cores: 1)
spawned uWSGI worker 3 (pid: 4863, cores: 1)
spawned uWSGI worker 4 (pid: 4864, cores: 1)
spawned uWSGI worker 5 (pid: 4865, cores: 1)
spawned uWSGI worker 6 (pid: 4866, cores: 1)
spawned uWSGI worker 7 (pid: 4867, cores: 1)
spawned uWSGI worker 8 (pid: 4868, cores: 1)
Traceback (most recent call last):
  File "./hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 14, in <module>
    from models import User
  File "./app/models.py", line 4, in <module>
    from app import db,app
ImportError: cannot import name db
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 4865|app: -1|req: -1/1] 123.121.145.251 () {46 vars in 911 bytes} [Sat Jul 15 13:24:57 2017] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (32bit) on [Sat Jul 15 13:28:07 2017] ***
compiled with version: 5.4.0 20160609 on 14 July 2017 20:12:54
os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:57:27 UTC 2017
nodename: iZ2zeg872luz0mzt03kfxzZ
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/flask/flask_blog-python3
writing pidfile to /var/run/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/flask/flask_blog-python3
your processes number limit is 7738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9163 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8763c60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 575856 bytes (562 KB) for 8 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 14, in <module>
    from models import User
  File "./app/models.py", line 4, in <module>
    from app import db,app
ImportError: cannot import name db
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4947)
spawned uWSGI worker 1 (pid: 4950, cores: 1)
spawned uWSGI worker 2 (pid: 4951, cores: 1)
spawned uWSGI worker 3 (pid: 4952, cores: 1)
spawned uWSGI worker 4 (pid: 4953, cores: 1)
spawned uWSGI worker 5 (pid: 4954, cores: 1)
spawned uWSGI worker 6 (pid: 4955, cores: 1)
spawned uWSGI worker 7 (pid: 4956, cores: 1)
spawned uWSGI worker 8 (pid: 4957, cores: 1)
Traceback (most recent call last):
  File "./hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 14, in <module>
    from models import User
  File "./app/models.py", line 4, in <module>
    from app import db,app
ImportError: cannot import name db
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 4954|app: -1|req: -1/1] 123.121.145.251 () {46 vars in 911 bytes} [Sat Jul 15 13:28:12 2017] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 18, in <module>
    manager=Manager(app)
NameError: name 'Manager' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 4955|app: -1|req: -1/2] 123.121.145.251 () {46 vars in 911 bytes} [Sat Jul 15 13:29:29 2017] GET / => generated 21 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Sat Jul 15 13:29:32 2017 - *** PAUSE (press start to resume, if you do not have a joypad send SIGTSTP) ***
Sat Jul 15 13:29:32 2017 - *** worker 2 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 1 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 3 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 4 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 7 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 5 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 8 suspended ***
Sat Jul 15 13:29:32 2017 - *** worker 6 suspended ***
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (32bit) on [Sat Jul 15 13:29:39 2017] ***
compiled with version: 5.4.0 20160609 on 14 July 2017 20:12:54
os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:57:27 UTC 2017
nodename: iZ2zeg872luz0mzt03kfxzZ
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/flask/flask_blog-python3
writing pidfile to /var/run/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/flask/flask_blog-python3
your processes number limit is 7738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9163 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8670c60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 575856 bytes (562 KB) for 8 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 18, in <module>
    manager=Manager(app)
NameError: name 'Manager' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5024)
spawned uWSGI worker 1 (pid: 5027, cores: 1)
spawned uWSGI worker 2 (pid: 5028, cores: 1)
spawned uWSGI worker 3 (pid: 5029, cores: 1)
spawned uWSGI worker 4 (pid: 5030, cores: 1)
spawned uWSGI worker 5 (pid: 5031, cores: 1)
spawned uWSGI worker 6 (pid: 5032, cores: 1)
spawned uWSGI worker 7 (pid: 5033, cores: 1)
spawned uWSGI worker 8 (pid: 5034, cores: 1)
Traceback (most recent call last):
  File "./hello.py", line 1, in <module>
    from app import app as application
  File "./app/__init__.py", line 18, in <module>
    manager=Manager(app)
NameError: name 'Manager' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 5030|app: -1|req: -1/1] 123.121.145.251 () {46 vars in 911 bytes} [Sat Jul 15 13:29:50 2017] GET / => generated 21 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8670c60 pid: 5029 (default app)
[pid: 5029|app: 0|req: 1/2] 123.121.145.251 () {46 vars in 911 bytes} [Sat Jul 15 13:30:39 2017] GET / => generated 12267 bytes in 159 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8670c60 pid: 5032 (default app)
[pid: 5032|app: 0|req: 1/3] 123.121.145.251 () {48 vars in 1103 bytes} [Sat Jul 15 13:30:41 2017] GET /fenlei/%E6%8E%A5%E5%8F%A3 => generated 14787 bytes in 149 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8670c60 pid: 5027 (default app)
[pid: 5027|app: 0|req: 1/4] 123.121.145.251 () {48 vars in 1118 bytes} [Sat Jul 15 13:30:42 2017] GET /fenlei/Jenkins => generated 15258 bytes in 140 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 5032|app: 0|req: 2/5] 123.121.145.251 () {48 vars in 1129 bytes} [Sat Jul 15 13:30:42 2017] GET /fenlei/%E6%95%B0%E6%8D%AE%E5%BA%93 => generated 15253 bytes in 31 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
[pid: 5027|app: 0|req: 2/6] 123.121.145.251 () {48 vars in 1109 bytes} [Sat Jul 15 13:30:44 2017] GET /login => generated 1515 bytes in 20 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 39, in login
    login_user(user)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 140, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'login_manager'
[pid: 5032|app: 0|req: 3/7] 123.121.145.251 () {54 vars in 1227 bytes} [Sat Jul 15 13:30:51 2017] POST /login => generated 0 bytes in 145 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 39, in login
    login_user(user)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 140, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'login_manager'
[pid: 5027|app: 0|req: 3/8] 123.121.145.251 () {54 vars in 1227 bytes} [Sat Jul 15 13:32:51 2017] POST /login => generated 0 bytes in 156 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 39, in login
    login_user(user)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 140, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'login_manager'
[pid: 5032|app: 0|req: 4/9] 123.121.145.251 () {54 vars in 1227 bytes} [Sat Jul 15 13:32:54 2017] POST /login => generated 0 bytes in 138 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
[pid: 5027|app: 0|req: 4/10] 123.121.145.251 () {46 vars in 1032 bytes} [Sat Jul 15 13:32:56 2017] GET /login => generated 1515 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8670c60 pid: 5028 (default app)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 39, in login
    login_user(user)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 140, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'login_manager'
[pid: 5028|app: 0|req: 1/11] 123.121.145.251 () {54 vars in 1227 bytes} [Sat Jul 15 13:33:03 2017] POST /login => generated 0 bytes in 204 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (32bit) on [Sat Jul 15 13:33:30 2017] ***
compiled with version: 5.4.0 20160609 on 14 July 2017 20:12:54
os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:57:27 UTC 2017
nodename: iZ2zeg872luz0mzt03kfxzZ
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/flask/flask_blog-python3
writing pidfile to /var/run/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/flask/flask_blog-python3
your processes number limit is 7738
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9163 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9536c60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 575856 bytes (562 KB) for 8 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9536c60 pid: 5076 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5076)
spawned uWSGI worker 1 (pid: 5079, cores: 1)
spawned uWSGI worker 2 (pid: 5080, cores: 1)
spawned uWSGI worker 3 (pid: 5081, cores: 1)
spawned uWSGI worker 4 (pid: 5082, cores: 1)
spawned uWSGI worker 5 (pid: 5083, cores: 1)
spawned uWSGI worker 6 (pid: 5084, cores: 1)
spawned uWSGI worker 7 (pid: 5085, cores: 1)
spawned uWSGI worker 8 (pid: 5086, cores: 1)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 39, in login
    login_user(user)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 140, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'login_manager'
[pid: 5083|app: 0|req: 1/1] 123.121.145.251 () {54 vars in 1227 bytes} [Sat Jul 15 13:33:36 2017] POST /login => generated 0 bytes in 162 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
[pid: 5086|app: 0|req: 1/2] 123.121.145.251 () {46 vars in 1032 bytes} [Sat Jul 15 13:33:38 2017] GET /login => generated 1515 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 39, in login
    login_user(user)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 140, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'login_manager'
[pid: 5081|app: 0|req: 1/3] 123.121.145.251 () {54 vars in 1227 bytes} [Sat Jul 15 13:33:42 2017] POST /login => generated 0 bytes in 173 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
./app/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=Baselogin()
[pid: 5086|app: 0|req: 2/4] 123.121.145.251 () {46 vars in 1032 bytes} [Sat Jul 15 13:33:45 2017] GET /login => generated 1515 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 5082|app: 0|req: 1/5] 123.121.145.251 () {48 vars in 1127 bytes} [Sat Jul 15 13:33:49 2017] GET /fenlei/Jenkins => generated 15258 bytes in 122 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
./app/views.py:76: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=CommentFrom()
[pid: 5086|app: 0|req: 3/6] 123.121.145.251 () {48 vars in 1093 bytes} [Sat Jul 15 13:33:53 2017] GET /post/23 => generated 5168 bytes in 79 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
./app/views.py:183: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=PostForm()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 186, in edit
    post_user=User.query.filter_by(id=post.user_id).first().username
AttributeError: 'NoneType' object has no attribute 'username'
[pid: 5081|app: 0|req: 2/7] 123.121.145.251 () {48 vars in 1086 bytes} [Sat Jul 15 13:33:57 2017] GET /edit/23 => generated 0 bytes in 19 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
./app/views.py:118: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = PostForm()
[pid: 5086|app: 0|req: 4/8] 123.121.145.251 () {48 vars in 1088 bytes} [Sat Jul 15 13:34:00 2017] GET /new_post => generated 4635 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
./app/views.py:183: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form=PostForm()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 186, in edit
    post_user=User.query.filter_by(id=post.user_id).first().username
AttributeError: 'NoneType' object has no attribute 'username'
[pid: 5081|app: 0|req: 3/9] 123.121.145.251 () {48 vars in 1086 bytes} [Sat Jul 15 13:34:04 2017] GET /edit/23 => generated 0 bytes in 15 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Sat Jul 15 13:34:43 2017 - *** PAUSE (press start to resume, if you do not have a joypad send SIGTSTP) ***
Sat Jul 15 13:34:43 2017 - *** worker 1 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 2 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 4 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 5 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 6 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 7 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 8 suspended ***
Sat Jul 15 13:34:43 2017 - *** worker 3 suspended ***
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
goodbye to uWSGI.
